version: "3.8"

services:
  nextjs:
    build: .
    ports:
      - "3001:3000"
    depends_on:
      - pdf2htmlex
    volumes:
      - .:/app
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - NODE_ENV=production

  pdf2htmlex:
    image: bwits/pdf2htmlex-alpine
    volumes:
      - ./public/uploads:/pdf
