services:
  - name: pdf-editor
    type: web
    env: docker
    repo: https://github.com/VrajVyas11/PDF-Manipulator
    dockerfilePath: ./Dockerfile
    envVars:
      - key: NODE_ENV
        value: production
    disk:
      name: uploads
      mountPath: /app/public/uploads
      sizeGB: 1  # Adjust as needed
    startCommand: npm install && npm run build && npm start
    healthCheckPath: /
    autoDeploy: true

  - name: pdf2html
    type: background
    env: docker
    image: bwits/pdf2htmlex-alpine
    startCommand: tail -f /dev/null
    disk:
      name: uploads
      mountPath: /pdf
      sizeGB: 1  # Shared storage with pdf-editor
