services:
  # Main PDF Editor Service
  - name: pdf-editor
    type: web
    runtime: docker
    repo: https://github.com/VrajVyas11/PDF-Manipulator
    rootDir: . 
    dockerfilePath: ./Dockerfile
    envVars:
      - key: NODE_ENV
        value: production
    disk:
      name: uploads
      mountPath: /app/public/uploads
      sizeGB: 1
    healthCheckPath: /
    autoDeploy: true
    scaling:
      minInstances: 1
      maxInstances: 3
      targetMemoryPercent: 60
      targetCPUPercent: 60

  # PDF-to-HTML Conversion Service
  - name: pdf2html
    type: pserv
    runtime: docker
    image:
      url: docker.io/bwits/pdf2htmlex-alpine  
    disk:
      name: uploads
      mountPath: /pdf
      sizeGB: 1
