export const navLinks = [
  {
    id: 'home',
    route: '',
    icon: '/images/home.svg',
    label: 'Home',
    description: 'Effortlessly combine multiple PDF documents into a single file for easier organization and sharing.',
    sideImage: '/images/detail-1.png',
  },
  {
    id: 'merge',
    route: '',
    icon: '/images/merge.svg',
    label: 'Merge PDF',
    description: 'Effortlessly combine multiple PDF documents into a single file for easier organization and sharing.',
    sideImage: '/images/detail-1.png',
  },
  {
    id: 'edit',
    route: '',
    icon: '/images/edit.svg',
    label: 'Edit PDF',
    description: 'Quickly and easily modify the content of your PDFs, including text, images, and layouts.',
    sideImage: '/images/detail-2.png',
  },
  {
    id: 'image',
    route: '',
    icon: '/images/ImageToPDF.svg',
    label: 'Image to PDF',
    description: 'Convert your images into high-quality PDFs in just a few clicks for secure and professional sharing.',
    sideImage: '/images/detail-3.png',
  },
  {
    id: 'compress',
    route: '',
    icon: '/images/compress.svg',
    label: 'Compress PDF',
    description: 'Easily reduce the file size of your PDFs for faster uploads and hassle-free sharing.',
    sideImage: '/images/detail-4.png',
  },
  {
    id: 'addpages',
    route: '',
    icon: '/addpages.svg',
    label: 'Add Pages',
    description: 'Insert new pages seamlessly into your PDF to expand or update your document as needed.',
    sideImage: '/images/plan-3.png',
  },
  {
    id: 'extract',
    route: '',
    icon: '/images/extractImages.svg',
    label: 'Extract Images',
    description: 'Effortlessly extract and save images from your PDFs for use in other documents or projects.',
    sideImage: '/images/plan-1.png',
  },
  {
    id: "LinkedIn",
    name: "LinkedIn",
    icon: "https://img.icons8.com/?size=100&id=xuvGCOXi8Wyg&format=png&color=000000",
    alt: "LinkedIn Icon",
    description:"",
    URL: "https://www.linkedin.com/in/vraj-vyas-983249297/"
  },

  {
    id: "GitHub",
    name: "GitHub",
    icon: "/images/github-logo.png",
    alt: "GitHub Icon",
    description:"",
    URL: "https://github.com/VrajVyas11/Next_JS_PDF_Manipulator"
  },
];
